kind: pipeline
type: docker
name: default

steps:
  - name: "Install and Build"
    image: node:14-alpine3.14
    failure: always
    commands:
      - yarn install --frozen-lockfile
      - yarn build

  - name: "Docker build latest"
    image: plugins/docker
    failure: always
    settings:
      repo: stiforr/strapi-backend
      auto_tag: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

  - name: "Release"
    image: node:14-alpine3.14
    failure: always
    commands:
      - yarn release
    depends_on:
      - "Install and Build"
      - "Docker build latest"
    environment:
      GH_TOKEN:
        from_secret: GH_TOKEN
    when:
      branch:
        include:
          - main
          - develop

trigger:
  branch:
    exclude:
      - renovate/*
