kind: pipeline
type: docker
name: default

steps:
  - name: "Install and Build"
    image: node:lts-buster
    commands:
      - yarn install --frozen-lockfile
      - yarn build
    environment:
      NEXT_PUBLIC_API_URL:
        from_secret: NEXT_PUBLIC_API_URL
      NEXT_PUBLIC_APIKEY:
        from_secret: NEXT_PUBLIC_APIKEY

  - name: "Docker build latest"
    image: plugins/docker
    settings:
      repo: stiforr/strapi-backend
      auto_tag: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

  - name: "Release"
    image: node:lts-buster
    commands:
      - yarn semantic-release
    depends_on:
      - "Install and Build"
      - "Docker build latest"
    environment:
      GH_TOKEN:
        from_secret: GH_TOKEN
    when:
      branch:
        include:
          - main
          - develop

trigger:
  branch:
    exclude:
      - renovate/*
